sudo: true

language: c

addons:
  postgresql: "9.3"
  apt:
    packages:
    - postgresql-server-dev-9.3
    - postgresql-common
    - liblwgeom-dev
    - libproj-dev
    - libgeos-dev

script:
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - make installcheck
