sudo: false

language: c

addons:
  postgresql: "9.3"
  apt:
    packages:
    - postgresql-server-dev-9.3
    - postgresql-common
    - liblwgeom-dev

script:
  - ./autogen.sh
  - ./configure
  - make
  - make install
  - make installcheck
