sudo: false

language: c

addons:
  postgresql: "9.3"
  apt:
    packages:
    - postgresql-server-dev-all
    - postgresql-common

script:
  - ./autogen.sh
  - ./configure
  - make
  - make install
  - make installcheck
